### ISSUE TITLE
is it normal that 60 Gi of memory is not enough?

### ISSUE THREAD

**Issue by Cui4399** [theochem/B3clf#27]
(b3clf_py37) ubuntu@iZ7xv3b7y4kl7qpjn9e3zmZ:~/B3clf$ free -h
              total        used        free      shared  buff/cache   available
Mem:           61Gi       191Mi        61Gi       2.0Mi       448Mi        61Gi
Swap:            0B          0B          0B
(b3clf_py37) ubuntu@iZ7xv3b7y4kl7qpjn9e3zmZ:~/B3clf$ b3clf -mol LANCL1.sdf -clf xgb -sampling classic_ADASYN -output LANCL1.csv -verbose 1
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/b3clf_py37/bin/b3clf", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/b3clf_py37/lib/python3.7/site-packages/b3clf/__main__.py", line 103, in main
    threshold=args.threshold,
  File "/home/ubuntu/anaconda3/envs/b3clf_py37/lib/python3.7/site-packages/b3clf/b3clf.py", line 116, in b3clf
    geometry_optimize(input_fname=mol_in, output_sdf=internal_sdf, sep=sep)
  File "/home/ubuntu/anaconda3/envs/b3clf_py37/lib/python3.7/site-packages/b3clf/geometry_opt.py", line 50, in geometry_optimize
    sep=sep)
  File "/home/ubuntu/anaconda3/envs/b3clf_py37/lib/python3.7/site-packages/b3clf/geometry_opt.py", line 138, in minimize_with_rdkit
    AllChem.EmbedMolecule(mol, randomSeed=999)
MemoryError
is it normal that 60 Gi of memory is not enough?

**Comment by PaulWAyers** [comment]
I think it is a bit weird. Probably the calculations needs to be staged, not doing the entire set at once.

**Comment by FanwangM** [comment]
I am not sure how big is your SDF file and how big are the molecules in the SDF file. But it seems it's a problem of geometry optimization with `RDKit`.  Can you try to split the big file into smaller batchers and see would that help? Any more information would help resolve the problem.  @Cui4399

**Comment by FanwangM** [comment]
Given that there is no update on this issuse, I am going to close it. But please feel free to reopen it. Thanks. @Cui4399
